"$schema" = 'https://starship.rs/config-schema.json'

palette = 'synthwave'

format = """
$directory\
[](bg:pill_secondary fg:pill_primary)\
$git_branch\
$git_status\
[ ](fg:pill_secondary)\
$character"""

right_format = """
$cmd_duration\
$time\
"""

[directory]
style = "bg:pill_primary fg:pill_primary_text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:pill_secondary_text bg:pill_secondary"
format = '[ $symbol $branch ]($style)'

[git_status]
format = '([ $conflicted$stashed$deleted$renamed$modified$typechanged$staged$untracked$ahead_behind ]($style))'
style = "bg:pill_secondary"
conflicted    = "[=${count}](fg:danger bg:pill_secondary)"
stashed       = "[\\$${count}](fg:info bg:pill_secondary)"
deleted       = "[✘${count}](fg:danger bg:pill_secondary)"
renamed       = "[»${count}](fg:accent bg:pill_secondary)"
modified      = "[!${count}](fg:warning bg:pill_secondary)"
typechanged   = "[±${count}](fg:attention bg:pill_secondary)"
staged        = "[+${count}](fg:success bg:pill_secondary)"
untracked     = "[?${count}](fg:notice bg:pill_secondary)"
ahead         = "[⇡${count}](fg:success bg:pill_secondary)"
behind        = "[⇣${count}](fg:attention bg:pill_secondary)"
diverged      = "[⇡${count_ahead}⇣${count_behind}](fg:info bg:pill_secondary)"

[time]
disabled = false
time_format = "%R"
style = "fg:muted"
format = '[  $time ]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'

[cmd_duration]
style = "fg:notice"
format = '[ $duration ]($style)'

[palettes.night_owl]
pill_primary = "#82aaff"
pill_primary_text = "#011627"
pill_secondary = "#1d3b53"
pill_secondary_text = "#22da6e"
muted = "#637777"
success = "#22da6e"
danger = "#ef5350"
warning = "#c5e478"
attention = "#f78c6c"
notice = "#7fdbca"
info = "#c792ea"
accent = "#82aaff"

[palettes.synthwave]
pill_primary = "#12c3e2"
pill_primary_text = "#000000"
pill_secondary = "#2a1b3d"
pill_secondary_text = "#1ebb2b"
muted = "#7f7094"
success = "#1ebb2b"
danger = "#f6188f"
warning = "#fdf834"
attention = "#f85a21"
notice = "#f841a0"
info = "#12c3e2"
accent = "#2186ec"
